import {
  FaCode,
  FaHtml5,
  FaCss3Alt,
  FaDatabase,
  FaLayerGroup,
  FaReact,
  FaBootstrap,
  FaMobileAlt,
  FaServer,
  FaNodeJs,
  FaKey,
  FaLock,
  FaTachometerAlt,
  FaListUl,
  FaProjectDiagram,
  FaShieldAlt,
  FaGlobe,
  FaCogs,
  FaWhatsapp,
  FaEnvelope,
  FaRupeeSign,
  FaGitAlt,
  FaGithub,
  FaCheckCircle,
  FaLeaf,
  FaCloud,
  FaBolt,
} from "react-icons/fa";
import {
  SiJavascript,
  SiTypescript,
  SiRedux,
  SiTailwindcss,
  SiExpress,
  SiJsonwebtokens,
  SiMongodb,
  SiMysql,
  SiPostman,
} from "react-icons/si";
import { TbBrandVscode } from "react-icons/tb";

export const iconMap = {
  code: FaCode,
  html5: FaHtml5,
  css3: FaCss3Alt,
  database: FaDatabase,
  layout: FaLayerGroup,
  layers: FaLayerGroup,
  react: FaReact,
  redux: SiRedux,
  tailwind: SiTailwindcss,
  bootstrap: FaBootstrap,
  responsive: FaMobileAlt,
  server: FaServer,
  node: FaNodeJs,
  express: SiExpress,
  api: FaProjectDiagram,
  jwt: SiJsonwebtokens,
  key: FaKey,
  lock: FaLock,
  mongodb: SiMongodb,
  leaf: FaLeaf,
  mysql: SiMysql,
  gauge: FaTachometerAlt,
  list: FaListUl,
  diagram: FaProjectDiagram,
  cloud: FaCloud,
  shield: FaShieldAlt,
  globe: FaGlobe,
  cogs: FaCogs,
  automation: FaBolt,
  whatsapp: FaWhatsapp,
  mail: FaEnvelope,
  payment: FaRupeeSign,
  javascript: SiJavascript,
  typescript: SiTypescript,
  git: FaGitAlt,
  github: FaGithub,
  postman: SiPostman,
  vscode: TbBrandVscode,
  review: FaCheckCircle,
};

export function SkillIcon({ name, className }) {
  const Icon = iconMap[name] || FaCode;
  return <Icon className={className} />;
}
